In [1]:
import numpy as np 


In [11]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [2, 3]])
b

array([[1, 2],
       [2, 3]])

In [5]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [6]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])